# Header
menu:
  Home: /
  Archives: /archives
rss: /rss2.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-81741124-1
favicon: /favicon.ico
twitter: RedNagaSec
google_plus:
fb_admins:
fb_app_id:
